version: '3.9'

services:
  app:
    container_name: test_app
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${UVICORN_PORT}:${UVICORN_PORT}"
    depends_on:
      - db
      - pgbouncer
    user: root
    volumes:
      - ./test_app:/app/test_app:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - postgresql_socket:/var/run/postgresql:rw
      - pip_cache:/pip_cache:rw
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@/${POSTGRES_DB}?host=/var/run/postgresql
      - UVICORN_NUMBER_WORKERS=${UVICORN_NUMBER_WORKERS}
      - UVICORN_LOG_LEVEL=${UVICORN_LOG_LEVEL}
      - UVICORN_PORT=${UVICORN_PORT}
    command: ["/bin/sh", "-c", "pip install --upgrade pip && pip install -r requirements.txt && uvicorn test_app.main:app --host 0.0.0.0 --port ${UVICORN_PORT} --workers ${UVICORN_NUMBER_WORKERS} --log-level ${UVICORN_LOG_LEVEL}"]
    
      
      
  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgresql_socket:/var/run/postgresql:rw
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 10
      timeout: 5s

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    depends_on:
      - db
    ports:
      - "6432:6432"
    volumes:
      - ./db/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./db/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
      - postgresql_socket:/var/run/postgresql:rw
      
  liquibase:
    image: liquibase/liquibase
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://db/${POSTGRES_DB}
      - LIQUIBASE_COMMAND_USERNAME=${POSTGRES_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${POSTGRES_PASSWORD}
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=${LIQUIBASE_COMMAND_CHANGELOG_FILE}
    command: update
    volumes:
      - ./db/liquibase/changelog:/liquibase/changelog
    depends_on:
      - db

volumes:
  postgresql_socket:
  pip_cache:


