version: '3.9'

services:
  app:
    build: .
    container_name: test_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://db_user:12345@pgbouncer:6432/${POSTGRES_DB}
    command: uvicorn test_app.main:app --host 0.0.0.0 --port 8000 --workers 8


  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 10
      timeout: 5s

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    depends_on:
      - db
    ports:
      - "6432:6432"
    volumes:
      - ./db/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./db/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt

  liquibase:
    image: liquibase/liquibase
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://db/${POSTGRES_DB}
      - LIQUIBASE_COMMAND_USERNAME=${POSTGRES_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${POSTGRES_PASSWORD}
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=/changelog/changelog_first.xml
    command: update
    volumes:
      - ./db/liquibase/changelog:/liquibase/changelog
    depends_on:
      - db



